import type { Locale } from "./i18n";

// Görsel adresleri — gerçek proje render'ları (public/renders klasöründe)
// Görsel adresleri — renk/pozlama düzeltilmiş render'lar (aydınlık, altın saat)
const IMG = {
  hero: "/renders/dis-cephe-gunbatimi.jpg",
  about: "/renders/teras-bahce.jpg",
  projHero: "/renders/hava-genel.jpg",
  // Daire içleri
  d1: "/renders/daire-salon-1.jpg",
  d2: "/renders/daire-salon-2.jpg",
  d3: "/renders/daire-genel.jpg",
  d4: "/renders/daire-mutfak.jpg",
  // Sosyal & çarşı
  pool: "/renders/avlu-havuz.jpg",
  social: "/renders/havuz-sezlong.jpg",
  carsi: "/renders/carsi-yaya.jpg",
  carsiCephe: "/renders/hava-carsi-yakin.jpg",
  // Genel
  facade: "/renders/dis-cephe-cadde.jpg",
  aerial: "/renders/hava-carsi.jpg",
  // Loft kesiti kanıt fotoğrafı (asma kat + metal merdiven görünüyor)
  loftProof: "/renders/loft-galeri-kanit.jpg",
};

export const SEGMENTS = {
  about: "about",
  projects: "projects",
  services: "services",
  contact: "contact",
  blog: "blog",
} as const;

const tr = {
  locale: "tr" as Locale,
  nav: {
    home: "Ana Sayfa",
    about: "Proje Hakkında",
    projects: "Daireler",
    services: "Neden Loft 777",
    blog: "Blog",
    contact: "İletişim",
    catalog: "Dijital Katalog",
    cta: "Fiyat Al",
  },
  hero: {
    kicker: "Camsan Koparan Group · Gaziemir / İzmir",
    lines: ["Gaziemir'de", "yeni nesil", "karma yaşam:"],
    last: "Loft 777.",
    sub: "Altında canlı bir çarşı, üstünde modern 1+1 daireler, ortasında havuzlu sosyal alan. İzmir Gaziemir'de yaşamak ve yatırım için tasarlanmış yeni bir adres.",
    ctaPrimary: "Fiyat & Kat Planı Al",
    ctaSecondary: "Bizi Arayın",
    video: "",
  },
  about: {
    kicker: "Loft 777 Hakkında",
    title1: "Şehrin içinde,",
    title2: "her şey ayağınızda.",
    body: "Loft 777; İzmir Gaziemir'de, market–kafe–mağazaların yer aldığı canlı çarşısı, yüzme havuzlu sosyal alanı ve modern 1+1 daireleriyle günlük hayatı tek bir adreste toplayan yeni nesil bir karma yaşam projesidir. Hem yaşamak hem de değer kazanan bir yatırım için tasarlandı.",
    badge: "TOPLAM DAİRE",
    more: "Projeyi Keşfedin",
    points: [
      { t: "Merkezi Konum", d: "Gaziemir'in kalbinde; ulaşım, alışveriş ve ana arterlere yakın bir lokasyon." },
      { t: "Karma Yaşam", d: "Zemin katta çarşı, üst katlarda konut — ihtiyacınız olan her şey aynı binada." },
      { t: "Akıllı 1+1 Daireler", d: "Pratik, modern ve fonksiyonel; hem yaşam hem yatırım için ideal planlar." },
    ],
  },
  aboutPage: {
    kicker: "Proje Hakkında",
    title: "Loft 777 — Gaziemir'de yeni nesil bir yaşam",
    intro: "Loft 777, Camsan Koparan Group A.Ş. tarafından İzmir Gaziemir'de geliştirilen, 237 daireli karma kullanımlı bir yaşam projesidir. Canlı çarşısı, havuzlu sosyal alanı ve modern 1+1 daireleriyle; konforu, ticareti ve sosyal yaşamı tek bir adreste buluşturur.",
    visionT: "Konsept",
    visionD: "Ticaret zeminde, sosyal yaşam ortada, huzur en üstte. Günün tamamını tek adreste, aşağı inmeden yaşamak üzerine kurulu bütünleşik bir konsept.",
    missionT: "Yaklaşımımız",
    missionD: "Modern mimari, kaliteli işçilik ve fonksiyonel daire planlarını bir araya getirerek; hem keyifli bir yaşam hem de sağlam bir yatırım sunmak.",
    specKicker: "Proje Künyesi",
    specTitle: "Rakamlarla Loft 777",
    specNote: "Bilgiler proje ruhsat ve uygulama projelerinden alınmıştır. Teslim tarihi planlanan tarihtir.",
    spec: [
      { k: "Konum", v: "Dokuz Eylül Mah. 694. Sk. No: 5 — Gaziemir / İzmir" },
      { k: "Blok Sayısı", v: "5 blok (A · B · C · D · E)" },
      { k: "Bağımsız Bölüm", v: "237" },
      { k: "Daire Tipleri", v: "1+1 Loft (~82 m²) · 1+1 Dubleks (49 m²)" },
      { k: "Tavan Yüksekliği", v: "Loft dairelerde 5,5 m (19,02 m² galeri boşluğu)" },
      { k: "Ticari Alan", v: "Zemin katta çarşı birimleri · 1 restoran" },
      { k: "Yeşil Alan", v: "4.200 m²" },
      { k: "Yüzme Havuzu", v: "150 m² açık havuz + çocuk havuzu" },
      { k: "Otopark", v: "Kapalı otopark" },
      { k: "Güvenlik", v: "7/24" },
      { k: "İnşaat Durumu", v: "Kaba inşaat aşamasında" },
      { k: "Planlanan Teslim", v: "Aralık 2027" },
    ],
    techKicker: "Yapı & Donanım",
    techTitle: "Görünmeyen kısım.",
    techBody: "Bir binanın değeri, taşındıktan sonra fark edilen şeylerde saklıdır. Loft 777'de gözle görünmeyen kalemler baştan çözüldü.",
    tech: [
      { t: "Deprem Yönetmeliği", d: "Güncel Türkiye Bina Deprem Yönetmeliği'ne tam uyumlu betonarme taşıyıcı sistem." },
      { t: "Merkezi Yerden Isıtma", d: "Tüm dairelerde yerden ısıtma; radyatör yok, duvarlar boşta, ısı dengeli dağılır." },
      { t: "VRF Klima", d: "Değişken debili sistem — her mekân ayrı ayarlanır, ortak dış ünite kirliliği olmaz." },
      { t: "Çift Cam Low-E", d: "Isı yalıtımlı kaplamalı cam: kışın ısıyı içeride, yazın dışarıda tutar." },
      { t: "Akıllı Ev Altyapısı", d: "Aydınlatma, iklimlendirme ve güvenlik için hazır kablolama; sonradan kırım gerekmez." },
      { t: "Kapalı Otopark", d: "Araç açık havada beklemez; iç mekândan doğrudan blok girişine bağlantı." },
    ],
    valuesT: "Öne Çıkanlar",
    values: [
      { t: "237 Daire", d: "Tamamı 1+1, iki farklı tip ve farklı cephe seçenekleriyle geniş bir yelpaze." },
      { t: "Canlı Çarşı", d: "Market, kafe, restoran ve mağazalar; kapından üç adım ötede günlük hayat." },
      { t: "Sosyal Yaşam", d: "Yüzme havuzu, geniş peyzaj alanları ve sosyal donatılar." },
      { t: "Güvenilir İmza", d: "Camsan Koparan Group A.Ş. güvencesiyle geliştirilen bir proje." },
    ],
  },
  // Proje künye şeridi (sahte istatistik yok, hepsi gerçek)
  stats: [
    { big: "237", small: "Daire" },
    { big: "1+1", small: "Daire Tipleri" },
    { big: "Çarşılı", small: "Karma Yaşam" },
    { big: "Gaziemir", small: "İzmir" },
  ],
  projectsHome: {
    kicker: "Proje",
    title1: "Tek imza,",
    title2: "eksiksiz bir yaşam.",
    all: "Projeyi İncele",
    incele: "İncele",
  },
  projectsPage: {
    kicker: "Daireler",
    title: "Loft 777 Daireleri",
    intro: "Gaziemir'in merkezinde iki 1+1 tipi: tavanı yükselen loft ve kompakt dubleks. Altında ise gün boyu yaşayan bir çarşı.",
    ongoing: "Devam Eden Proje",
    completed: "Tamamlanan Projeler",
    soon: "Yeni projelerimiz çok yakında bu sayfada.",
    detail: "Projeyi İncele",
  },
  services: {
    kicker: "Neden Loft 777?",
    title1: "Günlük hayatı",
    title2: "kolaylaştıran bir kurgu.",
    items: [
      { no: "01", t: "Merkezi Konum", d: "İzmir Gaziemir'de; ulaşım, alışveriş ve ana arterlere yakın değerli bir lokasyon." },
      { no: "02", t: "Çarşı & Ticaret", d: "Market, kafe, restoran ve mağazalarıyla canlı bir çarşı; kapının önünde günlük hayat." },
      { no: "03", t: "Sosyal Donatılar", d: "Yüzme havuzu, geniş peyzaj alanları ve keyifli ortak yaşam alanları." },
      { no: "04", t: "1+1 Daireler", d: "Pratik ve modern; hem yaşamak hem de kira getirisi için ideal daire planları." },
    ],
  },
  servicesPage: {
    kicker: "Neden Loft 777",
    title: "Loft 777'yi farklı kılan",
    intro: "Konum, çarşı, sosyal yaşam ve akıllı daire planları — hepsi tek bir projede.",
    payKicker: "Ödeme & Teslim",
    payTitle: "Koşullar açık.",
    payBody: "Ne ödeyeceğinizi ve ne zaman teslim alacağınızı baştan bilin. Aşağıdaki koşullar mevcut kampanya dönemi içindir.",
    payItems: [
      { k: "Peşinat", v: "%35", d: "Sözleşme aşamasında ödenir." },
      { k: "Vade", v: "18 ay", d: "Kalan tutar 18 aya kadar 0 faizle bölünür." },
      { k: "Peşin İndirimi", v: "%15", d: "Tamamı peşin ödemede uygulanır." },
      { k: "Planlanan Teslim", v: "Aralık 2027", d: "İnşaat kaba yapım aşamasında." },
    ],
    payNote: "Fiyat ve ödeme koşulları döneme göre değişebilir. Güncel liste için satış ekibimizle görüşün.",
    reasonsKicker: "Ayrıcalıklar",
    reasonsTitle: "Altı başlıkta Loft 777",
    reasons: [
      { t: "Ayrıcalıklı Konum", d: "Adnan Menderes Havalimanı'na 9 dakika, İZBAN Sarnıç durağı 800 metre. Optimum Outlet 4 dakika, otoban çıkışı 5 dakika." },
      { t: "Loft Konsepti", d: "Zemin katların tamamı loft: galeri boşluğuyla 5,5 metreye ulaşan tavan yüksekliği, açık plan ve içeri dolan doğal ışık." },
      { t: "Karma Yaşam", d: "Konut, çarşı, kafe ve restoran bir arada. Günlük ihtiyaçlar siteden çıkmadan, 4.200 m² yeşil alanın içinde karşılanır." },
      { t: "Yapı Kalitesi", d: "Güncel deprem yönetmeliğine tam uyum, merkezi yerden ısıtma, VRF klima, çift cam Low-E ve akıllı ev altyapısı." },
      { t: "Yatırım Değeri", d: "%35 peşin, 18 ay 0 faiz vade; peşin ödemede %15 indirim. Planlanan teslim: Aralık 2027." },
      { t: "Camsan Koparan Güvencesi", d: "1998'den bu yana İzmir'de konut, ticari ve endüstriyel yapı geliştiren köklü bir grubun imzası." },
    ],
  },
  cta: {
    kicker: "İletişim",
    title1: "Loft 777'de yerinizi",
    title2: "şimdiden ayırtın.",
    body: "Fiyat listesi, kat planları ve daire seçenekleri için bilgilerinizi bırakın; ekibimiz en kısa sürede size ulaşsın.",
    call: "Bizi Arayın",
    email: "E-posta Gönderin",
  },
  contactPage: {
    kicker: "İletişim",
    title: "Bize Ulaşın",
    intro: "Loft 777 hakkında fiyat, kat planı ve daire bilgileri için bizimle iletişime geçin.",
    visitKicker: "Ziyaret",
    visitTitle: "Projeyi yerinde görün.",
    visitBody: "Görüşmeler proje alanında yapılıyor. Gelmeden önce arayın; ekibimiz sizi karşılasın ve kat planlarını yanınızda inceleyelim.",
    hoursT: "Çalışma Saatleri",
    hoursWeek: "Pazartesi – Cumartesi",
    hoursWeekV: "08:00 – 18:00",
    hoursSun: "Pazar",
    hoursSunV: "Kapalı",
    routeT: "Yol Tarifi",
    routeCta: "Google Haritalar'da aç",
    addressT: "Adres",
    address: "Dokuz Eylül Mah. 694 Sok. No:5, Gaziemir / İzmir",
    phoneT: "Telefon",
    phone: "0232 237 7 237",
    mailT: "E-posta",
    mail: "info@camsankoparan.com",
    formName: "Ad Soyad",
    formMail: "E-posta",
    formPhone: "Telefon",
    formMsg: "Mesajınız",
    formSend: "Gönder",
  },
  footer: {
    tagline: "İzmir Gaziemir'de; çarşısı, havuzu ve modern 1+1 daireleriyle yeni nesil karma yaşam projesi. Camsan Koparan Group A.Ş. güvencesiyle.",
    cols: [
      { title: "Proje", links: [
        { label: "Daireler (1+1)", href: "projects/loft-777" },
        { label: "Sosyal Alanlar", href: "projects/loft-777" },
        { label: "Çarşı & Ticaret", href: "projects/loft-777" },
        { label: "Konum", href: "contact" },
      ] },
      { title: "Kurumsal", links: [
        { label: "Proje Hakkında", href: "about" },
        { label: "Camsan Koparan Group", href: "about" },
        { label: "Neden Loft 777", href: "services" },
      ] },
      { title: "İletişim", links: [
        { label: "Gaziemir / İzmir", href: "contact" },
        { label: "0232 237 7 237", href: "tel:+902322377237" },
        { label: "info@camsankoparan.com", href: "mailto:info@camsankoparan.com" },
      ] },
      { title: "Yasal", links: [
        { label: "KVKK Aydınlatma Metni", href: "kvkk" },
        { label: "Gizlilik Politikası", href: "gizlilik" },
        { label: "Çerez Politikası", href: "cerez-politikasi" },
        { label: "Çerez Tercihleri", href: "#consent" },
      ] },
    ],
    rights: "Tüm hakları saklıdır.",
    credit: "Tasarım & Yönetim",
  },
  cookieBanner: {
    title: "Çerez tercihiniz",
    body: "Zorunlu çerezleri kullanıyoruz. Ölçüm ve reklam çerezleri ise yalnızca izin verirseniz çalışır.",
    policyLink: "Çerez Politikası",
    acceptAll: "Tümünü Kabul Et",
    rejectAll: "Tümünü Reddet",
    customise: "Tercihlerimi seçeyim →",
    save: "Tercihimi Kaydet",
    necessary: "Zorunlu",
    necessaryDesc: "Site çalışsın diye gerekli; kapatılamaz.",
    analytics: "Analitik",
    analyticsDesc: "Hangi sayfaların ilgi gördüğünü görürüz (Google Analytics).",
    marketing: "Pazarlama",
    marketingDesc: "Reklam sonuçlarını ölçer (Meta, Google).",
  },
  legal: {
    updated: "Son güncelleme",
    other: "Diğer Yasal Metinler",
    names: { kvkk: "KVKK Aydınlatma Metni", privacy: "Gizlilik Politikası", cookies: "Çerez Politikası" },
  },
  callForm: {
    tab: "Sizi Arayalım",
    title: "Sizi Arayalım",
    sub: "Bilgilerinizi bırakın, ekibimiz en kısa sürede sizi arasın.",
    name: "Ad Soyad",
    phone: "Telefon",
    msg: "Mesajınız (opsiyonel)",
    send: "Gönder",
    sending: "Gönderiliyor…",
    success: "Teşekkürler! En kısa sürede sizi arayacağız.",
    error: "Bir hata oluştu, lütfen tekrar deneyin.",
  },
  formExtra: {
    unitLabel: "İlgilendiğiniz daire tipi",
    unitPlaceholder: "Daire tipi seçin (opsiyonel)",
    unitOptions: [
      { value: "1+1-a", label: "1+1 Loft" },
      { value: "1+1-b", label: "1+1 Dubleks" },
      { value: "farketmez", label: "Farketmez" },
    ],
    budgetPlaceholder: "Ödeme tercihi (opsiyonel)",
    budgetOptions: [
      { value: "pesin", label: "Peşin" },
      { value: "kredi", label: "Banka Kredisi" },
      { value: "taksit", label: "Taksit / Senet" },
      { value: "farketmez", label: "Farketmez" },
    ],
    kvkkText:
      "Kişisel verilerimin, benimle iletişime geçilmesi amacıyla işlenmesine onay veriyorum.",
    kvkkLink: "KVKK Aydınlatma Metni'ni okudum.",
    kvkkRequired: "Devam etmek için onay kutusunu işaretleyin.",
  },
  gallery: {
    kicker: "Galeri",
    title1: "Projeyi",
    title2: "yakından keşfedin.",
    hint: "Büyütmek için görsele tıklayın",
    categories: {
      all: "Tümü",
      exterior: "Dış Cephe",
      interior: "İç Mekan",
      social: "Sosyal Alan",
      commercial: "Çarşı",
    },
    items: [
      { img: "/renders/dis-cephe-gunbatimi.jpg", cat: "exterior", caption: "Loft 777 kuşbakışı — gün batımında avlu, havuz ve 5 blok yerleşimi" },
      { img: "/renders/dis-cephe-cadde.jpg", cat: "exterior", caption: "Loft 777 cadde cephesi ve zemin kat çarşısı — Gaziemir, İzmir" },
      { img: "/renders/hava-genel.jpg", cat: "exterior", caption: "Loft 777 genel yerleşim — otopark girişi ve çevre düzenlemesi" },
      { img: "/renders/hava-carsi.jpg", cat: "exterior", caption: "Loft 777 kuşbakışı — çarşı aksı ve cadde bağlantısı" },
      { img: "/renders/hava-carsi-yakin.jpg", cat: "exterior", caption: "Loft 777 çarşı cephesi ve teraslar — yakın görünüm" },
      { img: "/renders/daire-salon-1.jpg", cat: "interior", caption: "1+1 Loft daire salonu — 5,5 metre çift yükseklik yaşam alanı" },
      { img: "/renders/daire-salon-2.jpg", cat: "interior", caption: "1+1 daire salonu ve oturma grubu" },
      { img: "/renders/daire-salon-3.jpg", cat: "interior", caption: "1+1 daire yaşam alanı ve açık mutfak" },
      { img: "/renders/loft-galeri-kanit.jpg", cat: "interior", caption: "1+1 Loft — asma kat ve metal merdiven, salonun üstündeki galeri boşluğu" },
      { img: "/renders/daire-genel.jpg", cat: "interior", caption: "1+1 daire genel görünümü — salon ve mutfak" },
      { img: "/renders/daire-mutfak.jpg", cat: "interior", caption: "1+1 daire ankastre donanımlı mutfağı" },
      { img: "/renders/teras-bahce.jpg", cat: "interior", caption: "Loft 777 teras ve bahçe katı oturma alanı" },
      { img: "/renders/avlu-havuz.jpg", cat: "social", caption: "Loft 777 açık yüzme havuzu — 150 m² sosyal alan" },
      { img: "/renders/havuz-sezlong.jpg", cat: "social", caption: "Havuz çevresi şezlong alanı ve peyzaj" },
      { img: "/renders/havuz-sosyal.jpg", cat: "social", caption: "Havuzlu avluda sosyal yaşam — oturma ve dinlenme alanları" },
      { img: "/renders/avlu-havuz-2.jpg", cat: "social", caption: "Avlu ve havuz — üst kotdan görünüm" },
      { img: "/renders/bahce-aile.jpg", cat: "social", caption: "Yeşil alanlar ve aile kullanımına açık bahçe — 4.200 m²" },
      { img: "/renders/carsi-yaya.jpg", cat: "commercial", caption: "Çarşı yaya aksı — market, kafe ve mağazalar" },
      { img: "/renders/carsi-magaza.jpg", cat: "commercial", caption: "Loft 777 çarşısındaki mağazalar" },
      { img: "/renders/carsi-kafe.jpg", cat: "commercial", caption: "Loft 777 çarşısında kafe ve restoran alanı" },
    ],
  },
  construction: {
    kicker: "İnşaat Durumu",
    title1: "Açık süreç,",
    title2: "düzenli paylaşım.",
    status: "Kaba İnşaat Aşamasında",
    body: "İnşaat şu an kaba yapım aşamasında. İlerlemeyi düzenli olarak, hiçbir şeyi gizlemeden paylaşıyoruz.",
    steps: ["Temel & Kaba İnşaat", "İnce İşler", "Cephe & Peyzaj", "Teslim"],
    currentStep: 0,
    droneTitle: "Haftalık Drone Görüntüleri",
    droneSoon: "Güncel inşaat görselleri çok yakında burada paylaşılacak.",
  },
  faq: {
    kicker: "Sıkça Sorulan Sorular",
    title1: "Aklınızdaki",
    title2: "soruların yanıtı.",
    items: [
      {
        q: "Proje hangi aşamada, teslim ne zaman?",
        a: "Proje şu an kaba inşaat aşamasında; planlanan teslim tarihi Aralık 2027. Güncel takvim ve daire durumu için satış ekibimize ulaşabilirsiniz.",
      },
      {
        q: "Daire tipleri ve metrekareleri neler?",
        a: "İki farklı 1+1 tipi var: çift yükseklik salonlu (5,5 m tavan, 19 m² galeri boşluğu) ~82 m² Loft ve iki katlı 49 m² Dubleks. Kat planları için bizimle iletişime geçin.",
      },
      {
        q: "Fiyat bilgisini nasıl alabilirim?",
        a: "Fiyat listesi ve kat planları için sitedeki 'Fiyat Al' formunu doldurun; ekibimiz en kısa sürede size ulaşsın.",
      },
      {
        q: "Proje nerede, ulaşım nasıl?",
        a: "İzmir Gaziemir'de; havalimanı, İZBAN ve ana ulaşım akslarına yakın merkezi bir konumda.",
      },
      {
        q: "Sitede çarşı ve sosyal alanlar var mı?",
        a: "Evet. Zemin katta market, kafe ve mağazalardan oluşan bir çarşı; ortada yüzme havuzlu geniş bir sosyal alan yer alıyor.",
      },
      {
        q: "Yatırım için uygun mu?",
        a: "1+1 daireler ve altındaki canlı çarşısıyla proje; hem yaşam hem kira getirisi/yatırım için tasarlandı.",
      },
    ],
  },
  location: {
    kicker: "Lokasyon",
    title1: "Gaziemir'in",
    title2: "tam merkezinde.",
    body: "İzmir Gaziemir'de; ulaşımın, alışverişin ve günlük hayatın merkezinde ayrıcalıklı bir konum.",
    addressTitle: "Adres",
    mapQuery: "Gaziemir, İzmir, Türkiye",
    lat: 38.31779893739998,
    lng: 27.144827354238817,
    points: [
      { t: "Havalimanı", d: "Adnan Menderes Havalimanı'na 9 dk" },
      { t: "İZBAN", d: "İZBAN Sarnıç durağı 800 m" },
      { t: "Otoyol", d: "Otoyol çıkışına 5 dk" },
      { t: "Merkez", d: "İzmir merkezine 22 dk · Optimum Outlet 4 dk" },
    ],
  },
  catalog: {
    title: "Dijital Katalog",
    subtitle: "Loft 777 — Camsan Koparan Group 2026",
    hint: "Gezinmek için okları veya klavyeyi kullanın",
    pages: [
      { title: "Loft 777", caption: "Gaziemir'de yeni nesil karma yaşam — Tanıtım Kataloğu 2026", img: IMG.hero },
      { title: "Proje Konsepti", caption: "Otopark, çarşı, havuzlu avlu ve loft daireler; hepsi tek yapıda, dikey bir mahalle.", img: IMG.projHero },
      { title: "Lokasyon", caption: "İzmir Gaziemir — havalimanı, İZBAN ve ana arterlere yakın merkezi konum.", img: IMG.aerial },
      { title: "1+1 Daireler", caption: "İki farklı tipte, modern ve fonksiyonel 1+1 daireler.", img: IMG.d1 },
      { title: "İç Mekan", caption: "Akıllı planlı salon, açık mutfak ve şık bitiş malzemeleri.", img: IMG.d2 },
      { title: "Sosyal Yaşam", caption: "Yüzme havuzu, geniş peyzaj ve keyifli ortak yaşam alanları.", img: IMG.pool },
      { title: "Çarşı & Ticaret", caption: "Market, kafe ve mağazalarıyla gün boyu yaşayan bir çarşı.", img: IMG.carsi },
      { title: "İletişim", caption: "Gaziemir / İzmir — 0232 237 7 237 · info@camsankoparan.com", img: IMG.carsiCephe },
    ],
  },
  // TEZ CÜMLESİ — tek büyük cümle, sadece tipografi
  tez: {
    l1: "Zeminde çarşı.",
    l2: "Ortada havuz.",
    l3: "Üstte loft.",
  },
  notFound: {
    kicker: "404",
    title1: "Aradığınız sayfa",
    title2: "bulunamadı.",
    body: "Bağlantı taşınmış ya da hiç var olmamış olabilir. Loft 777'yi keşfetmeye ana sayfadan devam edebilirsiniz.",
    home: "Ana Sayfaya Dön",
    contact: "Bize Ulaşın",
  },
  // GALERİ BOŞLUĞU — dairenin kendi kesiti (ikinci imza).
  // Çift yükseklik planda görünmez, fotoğrafta anlaşılmaz; sadece kesitte okunur.
  loftKesit: {
    kicker: "1+1 Loft · Kesit",
    title1: "Salonun üstünde",
    title2: "tavan yok.",
    body: "Loft dairelerde salon iki kat boyunca yükseliyor. Üstünde döşeme değil, 19 m²'lik galeri boşluğu var — ışık yukarıdan iniyor, hacim aşağıya yayılıyor.",
    voidLabel: "Galeri Boşluğu",
    heightLabel: "çift yükseklik",
    stair: "Metal merdiven · 16 basamak",
    floors: { ground: "Zemin", mezzanine: "Asma Kat" },
    hint: "Mahalleri görmek için üzerine gelin",
    rooms: [
      { id: "salon", t: "Salon", m2: "40,86", floor: "ground" },
      { id: "mutfak", t: "Mutfak", m2: "9,75", floor: "ground" },
      { id: "yatak", t: "Yatak Odası", m2: "27,58", floor: "mezzanine" },
      { id: "banyo", t: "Banyo / WC", m2: "4,00", floor: "mezzanine" },
      { id: "galeri", t: "Galeri Boşluğu", m2: "19,02", floor: "void" },
    ],
    note: "Değerler C Blok kat planından alınmıştır; bloklar arasında farklılık gösterebilir.",
    proofImg: IMG.loftProof,
    proofAlt: "1+1 Loft dairenin iç mekanı: üstte asma kat, sağda metal merdiven, salonun üzerinde galeri boşluğu",
    proofCaption: "Aynı daire, içeriden: üstte asma kat, solda merdiven. Çift yükseklik ancak kesitte ölçülebilir — fotoğrafta hissedilir.",
  },
  // KESİT — imza bölüm: projenin dikey istifi (aşağıdan yukarı)
  kesit: {
    kicker: "Kesit",
    title1: "Arabanı bırak,",
    title2: "çarşıdan geç,",
    title3: "loft'una çık.",
    intro: "Loft 777 dikey bir mahalle: en altta kapalı otopark, ortada çarşı ve havuzlu avlu, en üstte 5,5 metre tavanlı loft daireler. Bütün bir hayat, aşağı inmeden elinin altında.",
    hint: "Katları görmek için kaydırın",
    layers: [
      {
        no: "−2 / −1",
        t: "Kapalı Otopark",
        d: "Daire başına bir araç. Elektrikli araç şarj istasyonlu, kartlı geçişli iki bodrum katı.",
        data: [
          { k: "238", v: "araçlık" },
          { k: "2", v: "bodrum kat" },
        ],
      },
      {
        no: "Zemin",
        t: "Çarşı & Sosyal Avlu",
        d: "Dışa dönük yüzde market, kafe ve restoran; içe dönük yüzde havuzlu yeşil avlu.",
        data: [
          { k: "150 m²", v: "açık havuz" },
          { k: "4.200 m²", v: "yeşil alan" },
        ],
      },
      {
        no: "Zemin + Asma",
        t: "1+1 Loft",
        d: "Salonun üstünde tavan yok. Galeri boşluğu sayesinde 5,5 metre çift yükseklik; asma katta yatak odası.",
        data: [
          { k: "5,5 m", v: "yükseklik" },
          { k: "~82 m²", v: "net alan" },
        ],
      },
      {
        no: "Üst Kat",
        t: "1+1 Dubleks & Teras",
        d: "İki katlı kompakt daireler ve site etrafını saran yürüyüş aksına açılan teraslar.",
        data: [
          { k: "49 m²", v: "net alan" },
          { k: "5", v: "blok" },
        ],
      },
    ],
  },
  seo: {
    home: {
      title: "Loft 777 — Gaziemir'de Satılık 1+1 Loft Daireler | Camsan Koparan",
      description: "İzmir Gaziemir'de 237 daireli yeni nesil karma yaşam projesi. Çift yükseklik loft daireler, açık havuz ve çarşı. %35 peşin, 18 ay 0 faiz. Fiyat & kat planı için arayın.",
    },
    about: {
      title: "Proje Hakkında — Loft 777 Gaziemir Karma Yaşam Projesi",
      description: "Loft 777; Gaziemir'de çarşısı, açık havuzu ve 1+1 loft/dubleks daireleriyle Camsan Koparan Group güvencesinde yeni nesil karma yaşam projesi.",
    },
    projects: {
      title: "Daireler — 1+1 Loft & Dubleks | Loft 777 Gaziemir",
      description: "Loft 777'de iki 1+1 tipi: 5,5 m çift yükseklik ~82 m² Loft ve 49 m² Dubleks. Gaziemir'de satılık modern daireler. Kat planı ve fiyat için iletişime geçin.",
    },
    project: {
      title: "Loft 777 — Gaziemir'de 1+1 Loft & Dubleks Daireler",
      description: "237 daireli Loft 777: çift yükseklik loft daireler, açık havuz, çarşı ve kapalı otopark. İzmir Gaziemir'de yaşam ve yatırım için.",
    },
    services: {
      title: "Neden Loft 777 — Gaziemir'de Yatırımlık 1+1 Daire",
      description: "Havalimanına 9 dk, İZBAN'a 800 m, çift yükseklik loft mimarisi ve canlı çarşı. Loft 777'yi Gaziemir'de öne çıkaran nedenler.",
    },
    kvkk: {
      title: "KVKK Aydınlatma Metni | Loft 777 — Camsan Koparan Group",
      description: "Camsan Koparan Group A.Ş. olarak kişisel verilerinizi hangi amaçla işlediğimizi, kimlere aktardığımızı ve 6698 sayılı Kanun kapsamındaki haklarınızı açıklar.",
    },
    privacy: {
      title: "Gizlilik Politikası | Loft 777 — Camsan Koparan Group",
      description: "camsankoparan.com'da hangi bilgileri topladığımızı, nasıl kullandığımızı, kimlerle paylaştığımızı ve nasıl koruduğumuzu açıklar.",
    },
    cookies: {
      title: "Çerez Politikası | Loft 777 — Camsan Koparan Group",
      description: "Sitemizde kullanılan zorunlu, analitik ve pazarlama çerezleri; Google Analytics ve Meta Pixel kullanımı ve çerezleri kapatma yolları.",
    },
    contact: {
      title: "İletişim — Loft 777 Satış Ofisi, Gaziemir",
      description: "Loft 777 satış ofisi: Dokuz Eylül Mah. 694 Sok. No:5, Gaziemir/İzmir · 0232 237 7 237. Fiyat ve kat planı için bize ulaşın.",
    },
  },
  project: {
    slug: "loft-777",
    name: "Loft 777",
    location: "Gaziemir, İzmir",
    status: "Kaba İnşaat Aşamasında",
    hero: IMG.projHero,
    tagline: "Çarşısı, havuzu ve modern 1+1 daireleriyle Gaziemir'de yeni nesil yaşam.",
    overviewT: "Proje Hakkında",
    overview: "Loft 777; İzmir Gaziemir'de, 237 daireli karma kullanımlı bir yaşam projesidir. Zemin katında market, kafe, restoran ve mağazalardan oluşan canlı bir çarşı; üst katlarında modern 1+1 daireler; ortasında ise yüzme havuzlu geniş bir sosyal alan yer alır. Görseller proje render'larından alınmıştır; inşaat şu anda kaba yapım aşamasındadır.",
    facts: [
      { k: "Konum", v: "Gaziemir, İzmir" },
      { k: "Durum", v: "Kaba İnşaat Aşamasında" },
      { k: "Daire Tipleri", v: "1+1 Loft & Dubleks" },
      { k: "Toplam Daire", v: "237 Daire" },
      { k: "Teslim", v: "Aralık 2027" },
      { k: "Ödeme", v: "%35 Peşin · 18 Ay 0 Faiz" },
    ],
    unitsT: "Daire Tipleri",
    unitsD: "İki farklı 1+1 konsepti: çift yükseklik loft ve iki katlı dubleks.",
    units: [
      { type: "1+1 Loft", size: "~82 m²", d: "Çift yükseklik salon — üstünde 5,5 metre galeri boşluğu. Zemin + asma kat, metal merdivenle bağlı.", img: IMG.d1 },
      { type: "1+1 Dubleks", size: "49 m²", d: "İki katlı, pratik ve modern yerleşimli 1+1 dubleks daire.", img: IMG.d2 },
    ],
    amenitiesT: "Sosyal Alanlar & Çarşı",
    amenitiesD: "Site içinde, ayağınıza gelen yaşam ve ticaret olanakları.",
    amenities: [
      { t: "Açık Yüzme Havuzu & Sosyal Alan", d: "150 m² açık havuz, çocuk havuzu, şezlong alanları ve geniş ortak yaşam alanları.", img: IMG.pool },
      { t: "Çarşı — Market & Mağazalar", d: "Market, mağaza ve hizmet birimlerinden oluşan canlı bir çarşı.", img: IMG.carsiCephe },
      { t: "Kafe & Restoran", d: "Site içinde kafe ve restoran alanları.", img: IMG.carsi },
      { t: "Peyzaj & Teraslar", d: "Yeşil peyzaj alanları, yürüyüş yolları ve geniş teraslar.", img: IMG.social },
    ],
    extras: ["Açık Yüzme Havuzu", "Fitness & Spor Salonu", "Çarşı & Market", "Kafe & Restoran", "Peyzaj & Yürüyüş Yolları", "Geniş Teraslar", "Kapalı Otopark", "7/24 Güvenlik"],
    galleryT: "Görseller",
    backToProjects: "Projeye Dön",
  },
};

const en: typeof tr = {
  locale: "en",
  nav: {
    home: "Home",
    about: "About the Project",
    projects: "Apartments",
    services: "Why Loft 777",
    blog: "Journal",
    contact: "Contact",
    catalog: "Digital Catalog",
    cta: "Get a Quote",
  },
  hero: {
    kicker: "Camsan Koparan Group · Gaziemir / Izmir",
    lines: ["A new way", "of living in", "Gaziemir:"],
    last: "Loft 777.",
    sub: "A lively shopping arcade below, modern 1+1 apartments above, and a pool-side social area at its heart. A new address in Izmir Gaziemir, designed both to live in and to invest.",
    ctaPrimary: "Get Price & Floor Plan",
    ctaSecondary: "Call Us",
    video: "",
  },
  about: {
    kicker: "About Loft 777",
    title1: "In the heart of the city,",
    title2: "everything at your feet.",
    body: "Loft 777 is a new-generation mixed-use project in Izmir Gaziemir that brings daily life together at a single address — with its lively arcade of markets, cafés and shops, its pool-side social area and its modern 1+1 apartments. Designed both to live in and as an appreciating investment.",
    badge: "TOTAL APARTMENTS",
    more: "Explore the Project",
    points: [
      { t: "Central Location", d: "In the heart of Gaziemir; close to transport, shopping and main arteries." },
      { t: "Mixed-Use Living", d: "An arcade on the ground floor, homes above — everything you need in one building." },
      { t: "Smart 1+1 Apartments", d: "Practical, modern and functional plans; ideal both to live in and to invest." },
    ],
  },
  aboutPage: {
    kicker: "About the Project",
    title: "Loft 777 — a new way of living in Gaziemir",
    intro: "Loft 777 is a 237-unit mixed-use living project developed by Camsan Koparan Group Inc. in Izmir Gaziemir. With its lively arcade, pool-side social area and modern 1+1 apartments, it brings comfort, commerce and social life together at a single address.",
    visionT: "Concept",
    visionD: "An arcade below, homes above and a pool-side social area at the centre — an integrated way of living where you can experience all of daily life within the site.",
    missionT: "Our Approach",
    missionD: "Bringing together modern architecture, quality workmanship and functional apartment plans to offer both an enjoyable life and a sound investment.",
    specKicker: "Project Data Sheet",
    specTitle: "Loft 777 in numbers",
    specNote: "Figures are taken from the permit and construction drawings. The delivery date is the planned date.",
    spec: [
      { k: "Location", v: "Dokuz Eylül Mah. 694. Sk. No: 5 — Gaziemir / Izmir" },
      { k: "Blocks", v: "5 blocks (A · B · C · D · E)" },
      { k: "Units", v: "237" },
      { k: "Apartment Types", v: "1+1 Loft (~82 m²) · 1+1 Duplex (49 m²)" },
      { k: "Ceiling Height", v: "5.5 m in loft units (19.02 m² void)" },
      { k: "Commercial Space", v: "Ground-floor retail units · 1 restaurant" },
      { k: "Green Space", v: "4,200 m²" },
      { k: "Swimming Pool", v: "150 m² outdoor pool + children’s pool" },
      { k: "Parking", v: "Covered car park" },
      { k: "Security", v: "24/7" },
      { k: "Construction Stage", v: "Structural works in progress" },
      { k: "Planned Delivery", v: "December 2027" },
    ],
    techKicker: "Build & Systems",
    techTitle: "The part you don’t see.",
    techBody: "A building’s worth lies in what you notice after moving in. At Loft 777 the invisible items were settled from the start.",
    tech: [
      { t: "Seismic Code", d: "Reinforced-concrete structure fully compliant with the current Turkish Building Earthquake Code." },
      { t: "Central Underfloor Heating", d: "Underfloor heating throughout; no radiators, walls stay free, heat spreads evenly." },
      { t: "VRF Air Conditioning", d: "Variable refrigerant flow — each room set separately, no clutter of outdoor units." },
      { t: "Low-E Double Glazing", d: "Coated insulating glass: keeps heat in through winter and out through summer." },
      { t: "Smart-Home Wiring", d: "Pre-wired for lighting, climate and security; no chasing walls later." },
      { t: "Covered Car Park", d: "Your car never waits outdoors; direct indoor link to the block entrance." },
    ],
    valuesT: "Highlights",
    values: [
      { t: "237 Apartments", d: "All 1+1, with two different types and varied façade options." },
      { t: "Lively Arcade", d: "Markets, cafés, restaurants and shops bringing commerce and services to your door." },
      { t: "Social Life", d: "Swimming pool, wide landscaped areas and social amenities." },
      { t: "A Trusted Signature", d: "A project developed under the assurance of Camsan Koparan Group Inc." },
    ],
  },
  stats: [
    { big: "237", small: "Apartments" },
    { big: "1+1", small: "Apartment Types" },
    { big: "Arcade", small: "Mixed-Use Living" },
    { big: "Gaziemir", small: "Izmir" },
  ],
  projectsHome: {
    kicker: "Project",
    title1: "One signature,",
    title2: "a complete life.",
    all: "View the Project",
    incele: "View",
  },
  projectsPage: {
    kicker: "Apartments",
    title: "Loft 777 Apartments",
    intro: "Modern 1+1 apartments and a lively arcade in the heart of Gaziemir.",
    ongoing: "Ongoing Project",
    completed: "Completed Projects",
    soon: "Our new projects are coming soon on this page.",
    detail: "View Project",
  },
  services: {
    kicker: "Why Loft 777?",
    title1: "A way of living that",
    title2: "makes life easier.",
    items: [
      { no: "01", t: "Central Location", d: "In Izmir Gaziemir; a valuable location close to transport, shopping and main arteries." },
      { no: "02", t: "Arcade & Commerce", d: "A lively arcade of markets, cafés, restaurants and shops; services at your door." },
      { no: "03", t: "Social Amenities", d: "Swimming pool, wide landscaped areas and enjoyable shared living spaces." },
      { no: "04", t: "1+1 Apartments", d: "Practical and modern; ideal both to live in and for rental income." },
    ],
  },
  servicesPage: {
    kicker: "Why Loft 777",
    title: "What sets Loft 777 apart",
    intro: "Location, arcade, social life and smart apartment plans — all in a single project.",
    payKicker: "Payment & Delivery",
    payTitle: "Clear terms.",
    payBody: "Know what you will pay and when you will take delivery, from the start. The terms below apply to the current campaign period.",
    payItems: [
      { k: "Down Payment", v: "35%", d: "Paid at the contract stage." },
      { k: "Instalments", v: "18 months", d: "The balance is split over up to 18 months at 0% interest." },
      { k: "Cash Discount", v: "15%", d: "Applied when paying in full." },
      { k: "Planned Delivery", v: "December 2027", d: "Structural works in progress." },
    ],
    payNote: "Prices and payment terms may change by period. Contact our sales team for the current list.",
    reasonsKicker: "Advantages",
    reasonsTitle: "Loft 777 in six points",
    reasons: [
      { t: "Prime Location", d: "9 minutes to Adnan Menderes Airport, 800 m to the İZBAN Sarnıç stop. Optimum Mall 4 minutes, motorway junction 5 minutes." },
      { t: "Loft Concept", d: "All ground floors are lofts: ceiling heights reaching 5.5 metres with the mezzanine void, open plans and natural light pouring in." },
      { t: "Mixed-Use Living", d: "Housing, arcade, café and restaurant together. Daily needs met without leaving the complex, within 4,200 m² of green space." },
      { t: "Build Quality", d: "Full compliance with the current seismic code, central underfloor heating, VRF air conditioning, double-glazed Low-E and smart-home infrastructure." },
      { t: "Investment Value", d: "35% down payment, 18 months interest-free; 15% discount on full payment. Planned delivery: December 2027." },
      { t: "Camsan Koparan Assurance", d: "Backed by an established group developing residential, commercial and industrial buildings in Izmir since 1998." },
    ],
  },
  cta: {
    kicker: "Contact",
    title1: "Reserve your place",
    title2: "at Loft 777 today.",
    body: "Leave your details for the price list, floor plans and apartment options, and our team will get back to you as soon as possible.",
    call: "Call Us",
    email: "Send an Email",
  },
  contactPage: {
    kicker: "Contact",
    title: "Get in Touch",
    intro: "Contact us for prices, floor plans and apartment details about Loft 777.",
    visitKicker: "Visit",
    visitTitle: "See the project on site.",
    visitBody: "Meetings take place on the project site. Call ahead so our team can meet you and go through the floor plans with you.",
    hoursT: "Opening Hours",
    hoursWeek: "Monday – Saturday",
    hoursWeekV: "08:00 – 18:00",
    hoursSun: "Sunday",
    hoursSunV: "Closed",
    routeT: "Directions",
    routeCta: "Open in Google Maps",
    addressT: "Address",
    address: "Dokuz Eylul Mah. 694 Sok. No:5, Gaziemir / Izmir",
    phoneT: "Phone",
    phone: "+90 232 237 7 237",
    mailT: "E-mail",
    mail: "info@camsankoparan.com",
    formName: "Full Name",
    formMail: "E-mail",
    formPhone: "Phone",
    formMsg: "Your Message",
    formSend: "Send",
  },
  footer: {
    tagline: "A new-generation mixed-use project in Izmir Gaziemir — with its arcade, pool and modern 1+1 apartments. Under the assurance of Camsan Koparan Group Inc.",
    cols: [
      { title: "Project", links: [
        { label: "Apartments (1+1)", href: "projects/loft-777" },
        { label: "Social Areas", href: "projects/loft-777" },
        { label: "Arcade & Commerce", href: "projects/loft-777" },
        { label: "Location", href: "contact" },
      ] },
      { title: "Corporate", links: [
        { label: "About the Project", href: "about" },
        { label: "Camsan Koparan Group", href: "about" },
        { label: "Why Loft 777", href: "services" },
      ] },
      { title: "Contact", links: [
        { label: "Gaziemir / Izmir", href: "contact" },
        { label: "+90 232 237 7 237", href: "tel:+902322377237" },
        { label: "info@camsankoparan.com", href: "mailto:info@camsankoparan.com" },
      ] },
      { title: "Legal", links: [
        { label: "Data Protection Notice", href: "kvkk" },
        { label: "Privacy Policy", href: "gizlilik" },
        { label: "Cookie Policy", href: "cerez-politikasi" },
        { label: "Cookie Preferences", href: "#consent" },
      ] },
    ],
    rights: "All rights reserved.",
    credit: "Design & Management",
  },
  cookieBanner: {
    title: "Your cookie choice",
    body: "We use strictly necessary cookies. Measurement and advertising cookies run only if you allow them.",
    policyLink: "Cookie Policy",
    acceptAll: "Accept All",
    rejectAll: "Reject All",
    customise: "Choose my preferences →",
    save: "Save My Choice",
    necessary: "Strictly necessary",
    necessaryDesc: "Needed for the site to work; cannot be disabled.",
    analytics: "Analytics",
    analyticsDesc: "Shows which pages draw interest (Google Analytics).",
    marketing: "Marketing",
    marketingDesc: "Measures advertising results (Meta, Google).",
  },
  legal: {
    updated: "Last updated",
    other: "Other Legal Documents",
    names: { kvkk: "Personal Data Protection Notice", privacy: "Privacy Policy", cookies: "Cookie Policy" },
  },
  callForm: {
    tab: "Call Me Back",
    title: "Request a Call",
    sub: "Leave your details and our team will call you back shortly.",
    name: "Full Name",
    phone: "Phone",
    msg: "Your message (optional)",
    send: "Send",
    sending: "Sending…",
    success: "Thank you! We will call you back shortly.",
    error: "Something went wrong, please try again.",
  },
  formExtra: {
    unitLabel: "Apartment type you're interested in",
    unitPlaceholder: "Select apartment type (optional)",
    unitOptions: [
      { value: "1+1-a", label: "1+1 Loft" },
      { value: "1+1-b", label: "1+1 Duplex" },
      { value: "farketmez", label: "No preference" },
    ],
    budgetPlaceholder: "Payment preference (optional)",
    budgetOptions: [
      { value: "pesin", label: "Cash" },
      { value: "kredi", label: "Bank Loan" },
      { value: "taksit", label: "Installments" },
      { value: "farketmez", label: "No preference" },
    ],
    kvkkText:
      "I consent to the processing of my personal data for the purpose of being contacted.",
    kvkkLink: "I have read the Personal Data Protection Notice.",
    kvkkRequired: "Please check the consent box to continue.",
  },
  gallery: {
    kicker: "Gallery",
    title1: "Explore the",
    title2: "project up close.",
    hint: "Click an image to enlarge",
    categories: {
      all: "All",
      exterior: "Exterior",
      interior: "Interior",
      social: "Social Area",
      commercial: "Arcade",
    },
    items: [
      { img: "/renders/dis-cephe-gunbatimi.jpg", cat: "exterior", caption: "Loft 777 aerial at sunset — courtyard, pool and the 5-block layout" },
      { img: "/renders/dis-cephe-cadde.jpg", cat: "exterior", caption: "Loft 777 street frontage and ground-floor arcade — Gaziemir, Izmir" },
      { img: "/renders/hava-genel.jpg", cat: "exterior", caption: "Loft 777 site overview — car park entrance and landscaping" },
      { img: "/renders/hava-carsi.jpg", cat: "exterior", caption: "Loft 777 aerial — arcade axis and street connection" },
      { img: "/renders/hava-carsi-yakin.jpg", cat: "exterior", caption: "Loft 777 arcade frontage and terraces — close view" },
      { img: "/renders/daire-salon-1.jpg", cat: "interior", caption: "1+1 Loft living room — 5.5 m double-height living space" },
      { img: "/renders/daire-salon-2.jpg", cat: "interior", caption: "1+1 apartment living room and seating area" },
      { img: "/renders/daire-salon-3.jpg", cat: "interior", caption: "1+1 apartment living space and open kitchen" },
      { img: "/renders/loft-galeri-kanit.jpg", cat: "interior", caption: "1+1 Loft — mezzanine and metal staircase, the void above the living room" },
      { img: "/renders/daire-genel.jpg", cat: "interior", caption: "1+1 apartment overview — living room and kitchen" },
      { img: "/renders/daire-mutfak.jpg", cat: "interior", caption: "1+1 apartment kitchen with built-in appliances" },
      { img: "/renders/teras-bahce.jpg", cat: "interior", caption: "Loft 777 terrace and garden-level seating" },
      { img: "/renders/avlu-havuz.jpg", cat: "social", caption: "Loft 777 outdoor swimming pool — 150 m² social area" },
      { img: "/renders/havuz-sezlong.jpg", cat: "social", caption: "Sun-lounger area and landscaping around the pool" },
      { img: "/renders/havuz-sosyal.jpg", cat: "social", caption: "Social life in the pool courtyard — seating and lounge areas" },
      { img: "/renders/avlu-havuz-2.jpg", cat: "social", caption: "Courtyard and pool — view from the upper level" },
      { img: "/renders/bahce-aile.jpg", cat: "social", caption: "Green areas and family-friendly garden — 4,200 m²" },
      { img: "/renders/carsi-yaya.jpg", cat: "commercial", caption: "Arcade pedestrian axis — market, café and shops" },
      { img: "/renders/carsi-magaza.jpg", cat: "commercial", caption: "Shops in the Loft 777 arcade" },
      { img: "/renders/carsi-kafe.jpg", cat: "commercial", caption: "Café and restaurant area in the Loft 777 arcade" },
    ],
  },
  construction: {
    kicker: "Construction Status",
    title1: "An open process,",
    title2: "shared regularly.",
    status: "Under Construction (Structural Phase)",
    body: "Construction is currently in the structural phase. We share progress regularly and openly, holding nothing back.",
    steps: ["Foundation & Structure", "Interior Works", "Façade & Landscape", "Delivery"],
    currentStep: 0,
    droneTitle: "Weekly Drone Footage",
    droneSoon: "Up-to-date construction visuals will be shared here very soon.",
  },
  faq: {
    kicker: "FAQ",
    title1: "Answers to",
    title2: "your questions.",
    items: [
      {
        q: "What stage is the project at, and when is delivery?",
        a: "The project is currently in the structural phase; the planned delivery date is December 2027. Contact our sales team for the current schedule and unit availability.",
      },
      {
        q: "What are the apartment types and sizes?",
        a: "There are two 1+1 types: a ~82 m² Loft with a double-height living room (5.5 m void) and a two-storey 49 m² Duplex. Contact us for floor plans.",
      },
      {
        q: "How can I get pricing information?",
        a: "Fill in the 'Get a Quote' form on the site for the price list and floor plans, and our team will reach out shortly.",
      },
      {
        q: "Where is the project and how is access?",
        a: "In Izmir Gaziemir; a central location close to the airport, the İZBAN rail line and main transport routes.",
      },
      {
        q: "Are there an arcade and social areas on site?",
        a: "Yes. A ground-floor arcade with a market, café and shops, plus a wide social area with a swimming pool at the centre.",
      },
      {
        q: "Is it suitable for investment?",
        a: "With its 1+1 apartments and the lively arcade below, the project is designed both for living and for rental income / investment.",
      },
    ],
  },
  location: {
    kicker: "Location",
    title1: "In the very heart",
    title2: "of Gaziemir.",
    body: "In Izmir Gaziemir; a privileged location at the centre of transport, shopping and daily life.",
    addressTitle: "Address",
    mapQuery: "Gaziemir, İzmir, Türkiye",
    lat: 38.31779893739998,
    lng: 27.144827354238817,
    points: [
      { t: "Airport", d: "9 min to Adnan Menderes Airport" },
      { t: "İZBAN", d: "800 m to İZBAN Sarnıç station" },
      { t: "Highway", d: "5 min to the highway exit" },
      { t: "Centre", d: "22 min to Izmir centre · Optimum Mall 4 min" },
    ],
  },
  catalog: {
    title: "Digital Catalog",
    subtitle: "Loft 777 — Camsan Koparan Group 2026",
    hint: "Use the arrows or your keyboard to navigate",
    pages: [
      { title: "Loft 777", caption: "A new way of living in Gaziemir — Brochure 2026", img: IMG.hero },
      { title: "Project Concept", caption: "A lively arcade below, modern homes above, a pool-side social area at the centre.", img: IMG.projHero },
      { title: "Location", caption: "Izmir Gaziemir — central, close to the airport, İZBAN rail and main arteries.", img: IMG.aerial },
      { title: "1+1 Apartments", caption: "Modern, functional 1+1 apartments in two different types.", img: IMG.d1 },
      { title: "Interiors", caption: "Smart-plan living room, open kitchen and refined finishes.", img: IMG.d2 },
      { title: "Social Life", caption: "Swimming pool, wide landscaping and enjoyable shared areas.", img: IMG.pool },
      { title: "Arcade & Commerce", caption: "A lively arcade with a market, café and shops at your door.", img: IMG.carsi },
      { title: "Contact", caption: "Gaziemir / Izmir — +90 232 237 7 237 · info@camsankoparan.com", img: IMG.carsiCephe },
    ],
  },
  tez: {
    l1: "An arcade below.",
    l2: "A pool between.",
    l3: "Lofts above.",
  },
  notFound: {
    kicker: "404",
    title1: "The page you're looking for",
    title2: "could not be found.",
    body: "The link may have moved or never existed. You can continue exploring Loft 777 from the home page.",
    home: "Back to Home",
    contact: "Contact Us",
  },
  loftKesit: {
    kicker: "1+1 Loft · Section",
    title1: "No ceiling above",
    title2: "the living room.",
    body: "In the loft apartments the living room rises through two floors. Above it there is no slab but a 19 m² void — light comes down from above, volume spreads below.",
    voidLabel: "Gallery Void",
    heightLabel: "double height",
    stair: "Metal staircase · 16 steps",
    floors: { ground: "Ground", mezzanine: "Mezzanine" },
    hint: "Hover to explore the spaces",
    rooms: [
      { id: "salon", t: "Living Room", m2: "40.86", floor: "ground" },
      { id: "mutfak", t: "Kitchen", m2: "9.75", floor: "ground" },
      { id: "yatak", t: "Bedroom", m2: "27.58", floor: "mezzanine" },
      { id: "banyo", t: "Bathroom / WC", m2: "4.00", floor: "mezzanine" },
      { id: "galeri", t: "Gallery Void", m2: "19.02", floor: "void" },
    ],
    note: "Figures are taken from the Block C floor plan; they may vary between blocks.",
    proofImg: IMG.loftProof,
    proofAlt: "Interior of the 1+1 Loft apartment: mezzanine above, metal staircase, the void over the living room",
    proofCaption: "The same apartment from inside: mezzanine above, staircase to the left. Double height can only be measured in section — but it is felt in a photograph.",
  },
  kesit: {
    kicker: "Section",
    title1: "Park below,",
    title2: "walk the arcade,",
    title3: "rise to your loft.",
    intro: "Loft 777 is a vertical neighbourhood: a closed car park at the bottom, an arcade and pool courtyard in the middle, and 5.5-metre-high loft apartments on top. A whole life within reach, without ever going down.",
    hint: "Scroll to reveal the levels",
    layers: [
      {
        no: "−2 / −1",
        t: "Closed Car Park",
        d: "One space per apartment. Two basement levels with EV charging and card access.",
        data: [
          { k: "238", v: "spaces" },
          { k: "2", v: "basement levels" },
        ],
      },
      {
        no: "Ground",
        t: "Arcade & Social Courtyard",
        d: "Market, café and restaurant on the outer face; a green courtyard with a pool on the inner face.",
        data: [
          { k: "150 m²", v: "outdoor pool" },
          { k: "4,200 m²", v: "green area" },
        ],
      },
      {
        no: "Ground + Mezzanine",
        t: "1+1 Loft",
        d: "No ceiling above the living room. A 5.5 m double height thanks to the void; bedroom on the mezzanine.",
        data: [
          { k: "5.5 m", v: "height" },
          { k: "~82 m²", v: "net area" },
        ],
      },
      {
        no: "Upper Floor",
        t: "1+1 Duplex & Terraces",
        d: "Compact two-storey apartments and terraces opening onto the walking route around the site.",
        data: [
          { k: "49 m²", v: "net area" },
          { k: "5", v: "blocks" },
        ],
      },
    ],
  },
  seo: {
    home: {
      title: "Loft 777 — 1+1 Loft Apartments for Sale in Gaziemir, Izmir",
      description: "A 237-unit new-generation mixed-use project in Izmir Gaziemir. Double-height loft apartments, outdoor pool and arcade. 35% down, 18-month 0% interest. Call for price & floor plan.",
    },
    about: {
      title: "About — Loft 777 Mixed-Use Project in Gaziemir, Izmir",
      description: "Loft 777: a new-generation mixed-use project in Gaziemir with its arcade, outdoor pool and 1+1 loft/duplex apartments, under Camsan Koparan Group.",
    },
    projects: {
      title: "Apartments — 1+1 Loft & Duplex | Loft 777 Gaziemir",
      description: "Two 1+1 types at Loft 777: a ~82 m² Loft with a 5.5 m double-height and a 49 m² Duplex. Modern apartments for sale in Gaziemir, Izmir.",
    },
    project: {
      title: "Loft 777 — 1+1 Loft & Duplex Apartments in Gaziemir",
      description: "237-unit Loft 777: double-height loft apartments, outdoor pool, arcade and closed parking in Izmir Gaziemir — to live in and to invest.",
    },
    services: {
      title: "Why Loft 777 — Investment 1+1 Apartments in Gaziemir",
      description: "9 min to the airport, 800 m to İZBAN, double-height loft architecture and a lively arcade. What sets Loft 777 apart in Gaziemir, Izmir.",
    },
    kvkk: {
      title: "Personal Data Protection Notice | Loft 777 — Camsan Koparan",
      description: "How Camsan Koparan Group Inc. processes your personal data, whom we share it with, and your rights under Turkish Law No. 6698.",
    },
    privacy: {
      title: "Privacy Policy | Loft 777 — Camsan Koparan Group",
      description: "What information camsankoparan.com collects, how we use it, whom we share it with and how we keep it secure.",
    },
    cookies: {
      title: "Cookie Policy | Loft 777 — Camsan Koparan Group",
      description: "Strictly necessary, analytics and marketing cookies on our site; our use of Google Analytics and Meta Pixel, and how to turn cookies off.",
    },
    contact: {
      title: "Contact — Loft 777 Sales Office, Gaziemir",
      description: "Loft 777 sales office: Dokuz Eylul Mah. 694 Sok. No:5, Gaziemir/Izmir · +90 232 237 7 237. Contact us for price and floor plans.",
    },
  },
  project: {
    slug: "loft-777",
    name: "Loft 777",
    location: "Gaziemir, Izmir",
    status: "Under Construction",
    hero: IMG.projHero,
    tagline: "A new way of living in Gaziemir, with its arcade, pool and modern 1+1 apartments.",
    overviewT: "About the Project",
    overview: "Loft 777 is a 237-unit mixed-use living project in Izmir Gaziemir. Its ground floor hosts a lively arcade of markets, cafés, restaurants and shops; its upper floors hold modern 1+1 apartments; and at its centre lies a wide social area with a swimming pool. Images are taken from project renders; construction is currently in the structural phase.",
    facts: [
      { k: "Location", v: "Gaziemir, Izmir" },
      { k: "Status", v: "Under Construction" },
      { k: "Unit Types", v: "1+1 Loft & Duplex" },
      { k: "Total Units", v: "237 Apartments" },
      { k: "Delivery", v: "December 2027" },
      { k: "Payment", v: "35% Down · 18 Mo 0% Interest" },
    ],
    unitsT: "Apartment Types",
    unitsD: "Two different 1+1 concepts: a double-height loft and a two-storey duplex.",
    units: [
      { type: "1+1 Loft", size: "~82 m²", d: "Double-height living room with a 5.5 m void above. Ground + mezzanine, linked by a metal staircase.", img: IMG.d1 },
      { type: "1+1 Duplex", size: "49 m²", d: "A two-storey, practical and modern 1+1 duplex apartment.", img: IMG.d2 },
    ],
    amenitiesT: "Social Areas & Arcade",
    amenitiesD: "Living and commerce facilities right at your doorstep within the site.",
    amenities: [
      { t: "Outdoor Swimming Pool & Social Area", d: "150 m² outdoor pool, kids' pool, lounge areas and wide shared living spaces.", img: IMG.pool },
      { t: "Arcade — Markets & Shops", d: "A lively arcade of markets, shops and service units.", img: IMG.carsiCephe },
      { t: "Café & Restaurant", d: "On-site café and restaurant areas.", img: IMG.carsi },
      { t: "Landscape & Terraces", d: "Green landscaped areas, walking paths and wide terraces.", img: IMG.social },
    ],
    extras: ["Outdoor Swimming Pool", "Fitness & Gym", "Arcade & Market", "Café & Restaurant", "Landscape & Walking Paths", "Wide Terraces", "Closed Parking", "24/7 Security"],
    galleryT: "Gallery",
    backToProjects: "Back to Project",
  },
};

export type Dict = typeof tr;

export function getDict(locale: Locale): Dict {
  return locale === "en" ? en : tr;
}
