import type { Locale } from "./i18n";

// Görsel adresleri — gerçek proje render'ları (public/renders klasöründe)
const IMG = {
  hero: "/renders/dis-cephe-gece-1.jpg",
  about: "/renders/teras-balkon.jpg",
  projHero: "/renders/hava-genel-gece.jpg",
  // Daire içleri
  d1: "/renders/daire-salon-1.jpg",
  d2: "/renders/daire-salon-2.jpg",
  d3: "/renders/daire-genel.jpg",
  d4: "/renders/daire-mutfak.jpg",
  // Sosyal & çarşı
  pool: "/renders/avlu-havuz-kus.jpg",
  social: "/renders/sosyal-alan.jpg",
  carsi: "/renders/carsi-kafe.jpg",
  carsiCephe: "/renders/carsi-cephe.jpg",
  // Genel
  facade: "/renders/dis-cephe-genel.jpg",
  aerial: "/renders/hava-tepeden.jpg",
};

export const SEGMENTS = {
  about: "about",
  projects: "projects",
  services: "services",
  contact: "contact",
} as const;

const tr = {
  locale: "tr" as Locale,
  nav: {
    home: "Ana Sayfa",
    about: "Proje Hakkında",
    projects: "Daireler",
    services: "Neden Loft 777",
    contact: "İletişim",
    catalog: "Dijital Katalog",
    cta: "Fiyat Al",
  },
  hero: {
    kicker: "Camsan Koparan Group · Gaziemir / İzmir",
    lines: ["Gaziemir'de", "yeni nesil", "karma yaşam:"],
    last: "Loft 777.",
    sub: "Altında canlı bir çarşı, üstünde modern 1+1 daireler, ortasında havuzlu sosyal alan. İzmir Gaziemir'de yaşamak ve yatırım için tasarlanmış yeni bir adres.",
    ctaPrimary: "Fiyat & Kat Planı Al",
    ctaSecondary: "Bizi Arayın",
    video: "",
  },
  about: {
    kicker: "Loft 777 Hakkında",
    title1: "Şehrin içinde,",
    title2: "her şey ayağınızda.",
    body: "Loft 777; İzmir Gaziemir'de, market–kafe–mağazaların yer aldığı canlı çarşısı, yüzme havuzlu sosyal alanı ve modern 1+1 daireleriyle günlük hayatı tek bir adreste toplayan yeni nesil bir karma yaşam projesidir. Hem yaşamak hem de değer kazanan bir yatırım için tasarlandı.",
    badge: "TOPLAM DAİRE",
    more: "Projeyi Keşfedin",
    points: [
      { t: "Merkezi Konum", d: "Gaziemir'in kalbinde; ulaşım, alışveriş ve ana arterlere yakın bir lokasyon." },
      { t: "Karma Yaşam", d: "Zemin katta çarşı, üst katlarda konut — ihtiyacınız olan her şey aynı binada." },
      { t: "Akıllı 1+1 Daireler", d: "Pratik, modern ve fonksiyonel; hem yaşam hem yatırım için ideal planlar." },
    ],
  },
  aboutPage: {
    kicker: "Proje Hakkında",
    title: "Loft 777 — Gaziemir'de yeni nesil bir yaşam",
    intro: "Loft 777, Camsan Koparan Group A.Ş. tarafından İzmir Gaziemir'de geliştirilen, 238 daireli karma kullanımlı bir yaşam projesidir. Canlı çarşısı, havuzlu sosyal alanı ve modern 1+1 daireleriyle; konforu, ticareti ve sosyal yaşamı tek bir adreste buluşturur.",
    visionT: "Konsept",
    visionD: "Altında çarşı, üstünde konut, ortasında havuzlu sosyal alan — günlük hayatın tamamını site içinde yaşayabileceğiniz bütünleşik bir yaşam kurgusu.",
    missionT: "Yaklaşımımız",
    missionD: "Modern mimari, kaliteli işçilik ve fonksiyonel daire planlarını bir araya getirerek; hem keyifli bir yaşam hem de sağlam bir yatırım sunmak.",
    valuesT: "Öne Çıkanlar",
    values: [
      { t: "238 Daire", d: "Tamamı 1+1, iki farklı tip ve farklı cephe seçenekleriyle geniş bir yelpaze." },
      { t: "Canlı Çarşı", d: "Market, kafe, restoran ve mağazalarla ayağınıza gelen ticaret ve hizmet." },
      { t: "Sosyal Yaşam", d: "Yüzme havuzu, geniş peyzaj alanları ve sosyal donatılar." },
      { t: "Güvenilir İmza", d: "Camsan Koparan Group A.Ş. güvencesiyle geliştirilen bir proje." },
    ],
  },
  // Proje künye şeridi (sahte istatistik yok, hepsi gerçek)
  stats: [
    { big: "238", small: "Daire" },
    { big: "1+1", small: "Daire Tipleri" },
    { big: "Çarşılı", small: "Karma Yaşam" },
    { big: "Gaziemir", small: "İzmir" },
  ],
  projectsHome: {
    kicker: "Proje",
    title1: "Tek imza,",
    title2: "eksiksiz bir yaşam.",
    all: "Projeyi İncele",
    incele: "İncele",
  },
  projectsPage: {
    kicker: "Daireler",
    title: "Loft 777 Daireleri",
    intro: "Gaziemir'in merkezinde, modern 1+1 daireler ve canlı bir çarşı.",
    ongoing: "Devam Eden Proje",
    completed: "Tamamlanan Projeler",
    soon: "Yeni projelerimiz çok yakında bu sayfada.",
    detail: "Projeyi İncele",
  },
  services: {
    kicker: "Neden Loft 777?",
    title1: "Yaşamı kolaylaştıran",
    title2: "bir yaşam kurgusu.",
    items: [
      { no: "01", t: "Merkezi Konum", d: "İzmir Gaziemir'de; ulaşım, alışveriş ve ana arterlere yakın değerli bir lokasyon." },
      { no: "02", t: "Çarşı & Ticaret", d: "Market, kafe, restoran ve mağazalarıyla canlı bir çarşı; ayağınıza gelen hizmet." },
      { no: "03", t: "Sosyal Donatılar", d: "Yüzme havuzu, geniş peyzaj alanları ve keyifli ortak yaşam alanları." },
      { no: "04", t: "1+1 Daireler", d: "Pratik ve modern; hem yaşamak hem de kira getirisi için ideal daire planları." },
    ],
  },
  servicesPage: {
    kicker: "Neden Loft 777",
    title: "Loft 777'yi farklı kılan",
    intro: "Konum, çarşı, sosyal yaşam ve akıllı daire planları — hepsi tek bir projede.",
  },
  cta: {
    kicker: "İletişim",
    title1: "Loft 777'de yerinizi",
    title2: "şimdiden ayırtın.",
    body: "Fiyat listesi, kat planları ve daire seçenekleri için bilgilerinizi bırakın; ekibimiz en kısa sürede size ulaşsın.",
    call: "Bizi Arayın",
    email: "E-posta Gönderin",
  },
  contactPage: {
    kicker: "İletişim",
    title: "Bize Ulaşın",
    intro: "Loft 777 hakkında fiyat, kat planı ve daire bilgileri için bizimle iletişime geçin.",
    addressT: "Adres",
    address: "Dokuz Eylül Mah. 694 Sok. No:5, Gaziemir / İzmir",
    phoneT: "Telefon",
    phone: "0232 237 7 237",
    mailT: "E-posta",
    mail: "info@camsankoparan.com",
    formName: "Ad Soyad",
    formMail: "E-posta",
    formPhone: "Telefon",
    formMsg: "Mesajınız",
    formSend: "Gönder",
  },
  footer: {
    tagline: "İzmir Gaziemir'de; çarşısı, havuzu ve modern 1+1 daireleriyle yeni nesil karma yaşam projesi. Camsan Koparan Group A.Ş. güvencesiyle.",
    cols: [
      { title: "Proje", links: ["Daireler (1+1)", "Sosyal Alanlar", "Çarşı & Ticaret", "Konum"] },
      { title: "Kurumsal", links: ["Proje Hakkında", "Camsan Koparan Group", "Neden Loft 777"] },
      { title: "İletişim", links: ["Gaziemir / İzmir", "0232 237 7 237", "info@camsankoparan.com"] },
    ],
    rights: "Tüm hakları saklıdır.",
    credit: "Tasarım & Yönetim",
  },
  callForm: {
    tab: "Sizi Arayalım",
    title: "Sizi Arayalım",
    sub: "Bilgilerinizi bırakın, ekibimiz en kısa sürede sizi arasın.",
    name: "Ad Soyad",
    phone: "Telefon",
    msg: "Mesajınız (opsiyonel)",
    send: "Gönder",
    sending: "Gönderiliyor…",
    success: "Teşekkürler! En kısa sürede sizi arayacağız.",
    error: "Bir hata oluştu, lütfen tekrar deneyin.",
  },
  formExtra: {
    unitLabel: "İlgilendiğiniz daire tipi",
    unitPlaceholder: "Daire tipi seçin (opsiyonel)",
    unitOptions: [
      { value: "1+1-a", label: "1+1 A Tipi" },
      { value: "1+1-b", label: "1+1 B Tipi" },
      { value: "farketmez", label: "Farketmez" },
    ],
    kvkkText:
      "Kişisel verilerimin, benimle iletişime geçilmesi amacıyla işlenmesine onay veriyorum.",
    kvkkRequired: "Devam etmek için onay kutusunu işaretleyin.",
  },
  gallery: {
    kicker: "Galeri",
    title1: "Projeyi",
    title2: "yakından keşfedin.",
    hint: "Büyütmek için görsele tıklayın",
    categories: {
      all: "Tümü",
      exterior: "Dış Cephe",
      interior: "İç Mekan",
      social: "Sosyal Alan",
      commercial: "Çarşı",
    },
    items: [
      { img: "/renders/dis-cephe-gece-1.jpg", cat: "exterior", caption: "Dış cephe — gece" },
      { img: "/renders/dis-cephe-aksam.jpg", cat: "exterior", caption: "Dış cephe — akşam" },
      { img: "/renders/dis-cephe-genel.jpg", cat: "exterior", caption: "Genel görünüm" },
      { img: "/renders/hava-genel-gece.jpg", cat: "exterior", caption: "Kuşbakışı — gece" },
      { img: "/renders/hava-tepeden.jpg", cat: "exterior", caption: "Tepeden görünüm" },
      { img: "/renders/daire-salon-1.jpg", cat: "interior", caption: "Salon" },
      { img: "/renders/daire-salon-2.jpg", cat: "interior", caption: "Salon & oturma" },
      { img: "/renders/daire-salon-3.jpg", cat: "interior", caption: "Yaşam alanı" },
      { img: "/renders/daire-genel.jpg", cat: "interior", caption: "Daire genel" },
      { img: "/renders/daire-mutfak.jpg", cat: "interior", caption: "Mutfak" },
      { img: "/renders/teras-balkon.jpg", cat: "interior", caption: "Teras & balkon" },
      { img: "/renders/avlu-havuz-kus.jpg", cat: "social", caption: "Yüzme havuzu" },
      { img: "/renders/sosyal-alan.jpg", cat: "social", caption: "Sosyal yaşam alanı" },
      { img: "/renders/carsi-cephe.jpg", cat: "commercial", caption: "Çarşı cephesi" },
      { img: "/renders/carsi-magaza.jpg", cat: "commercial", caption: "Mağazalar" },
      { img: "/renders/carsi-kafe.jpg", cat: "commercial", caption: "Kafe & restoran" },
      { img: "/renders/carsi-gece.jpg", cat: "commercial", caption: "Çarşı — gece" },
    ],
  },
  construction: {
    kicker: "İnşaat Durumu",
    title1: "Şeffaf süreç,",
    title2: "her hafta güncel.",
    status: "Kaba İnşaat Aşamasında",
    body: "İnşaatımız şu an kaba yapım aşamasında. Süreci şeffaf yürütüyor, ilerlemeyi her hafta güncel drone görüntüleriyle paylaşacağız.",
    steps: ["Temel & Kaba İnşaat", "İnce İşler", "Cephe & Peyzaj", "Teslim"],
    currentStep: 0,
    droneTitle: "Haftalık Drone Görüntüleri",
    droneSoon: "Güncel inşaat görselleri çok yakında burada paylaşılacak.",
  },
  faq: {
    kicker: "Sıkça Sorulan Sorular",
    title1: "Aklınızdaki",
    title2: "soruların yanıtı.",
    items: [
      {
        q: "Proje hangi aşamada, teslim ne zaman?",
        a: "Proje şu an kaba inşaat aşamasında. Net teslim tarihi için satış ekibimizle iletişime geçebilirsiniz.",
      },
      {
        q: "Daire tipleri ve metrekareleri neler?",
        a: "Tüm daireler 1+1; iki farklı tip ve farklı cephe seçenekleri mevcut. Güncel metrekare ve kat planları için bizimle iletişime geçin.",
      },
      {
        q: "Fiyat bilgisini nasıl alabilirim?",
        a: "Fiyat listesi ve kat planları için sitedeki 'Fiyat Al' formunu doldurun; ekibimiz en kısa sürede size ulaşsın.",
      },
      {
        q: "Proje nerede, ulaşım nasıl?",
        a: "İzmir Gaziemir'de; havalimanı, İZBAN ve ana ulaşım akslarına yakın merkezi bir konumda.",
      },
      {
        q: "Sitede çarşı ve sosyal alanlar var mı?",
        a: "Evet. Zemin katta market, kafe ve mağazalardan oluşan bir çarşı; ortada yüzme havuzlu geniş bir sosyal alan yer alıyor.",
      },
      {
        q: "Yatırım için uygun mu?",
        a: "1+1 daireler ve altındaki canlı çarşısıyla proje; hem yaşam hem kira getirisi/yatırım için tasarlandı.",
      },
    ],
  },
  location: {
    kicker: "Lokasyon",
    title1: "Gaziemir'in",
    title2: "tam merkezinde.",
    body: "İzmir Gaziemir'de; ulaşımın, alışverişin ve günlük hayatın merkezinde ayrıcalıklı bir konum.",
    addressTitle: "Adres",
    mapQuery: "Gaziemir, İzmir, Türkiye",
    points: [
      { t: "Havalimanı", d: "Adnan Menderes Havalimanı'na yakın" },
      { t: "İZBAN & Ulaşım", d: "Banliyö treni ve ana arterlere kolay erişim" },
      { t: "Otoyol", d: "Çevre yolu ve otoyol bağlantılarına yakın" },
      { t: "Merkez", d: "Alışveriş, okul ve günlük ihtiyaçlar yakında" },
    ],
  },
  catalog: {
    title: "Dijital Katalog",
    subtitle: "Loft 777 — Camsan Koparan Group 2026",
    hint: "Gezinmek için okları veya klavyeyi kullanın",
    pages: [
      { title: "Loft 777", caption: "Gaziemir'de yeni nesil karma yaşam — Tanıtım Kataloğu 2026", img: IMG.hero },
      { title: "Proje Konsepti", caption: "Altında canlı çarşı, üstünde modern konut, ortasında havuzlu sosyal alan.", img: IMG.projHero },
      { title: "Lokasyon", caption: "İzmir Gaziemir — havalimanı, İZBAN ve ana arterlere yakın merkezi konum.", img: IMG.aerial },
      { title: "1+1 Daireler", caption: "İki farklı tipte, modern ve fonksiyonel 1+1 daireler.", img: IMG.d1 },
      { title: "İç Mekan", caption: "Akıllı planlı salon, açık mutfak ve şık bitiş malzemeleri.", img: IMG.d2 },
      { title: "Sosyal Yaşam", caption: "Yüzme havuzu, geniş peyzaj ve keyifli ortak yaşam alanları.", img: IMG.pool },
      { title: "Çarşı & Ticaret", caption: "Market, kafe ve mağazalarla ayağınıza gelen canlı bir çarşı.", img: IMG.carsi },
      { title: "İletişim", caption: "Gaziemir / İzmir — 0232 237 7 237 · info@camsankoparan.com", img: IMG.carsiCephe },
    ],
  },
  project: {
    slug: "loft-777",
    name: "Loft 777",
    location: "Gaziemir, İzmir",
    status: "Kaba İnşaat Aşamasında",
    hero: IMG.projHero,
    tagline: "Çarşısı, havuzu ve modern 1+1 daireleriyle Gaziemir'de yeni nesil yaşam.",
    overviewT: "Proje Hakkında",
    overview: "Loft 777; İzmir Gaziemir'de, 238 daireli karma kullanımlı bir yaşam projesidir. Zemin katında market, kafe, restoran ve mağazalardan oluşan canlı bir çarşı; üst katlarında modern 1+1 daireler; ortasında ise yüzme havuzlu geniş bir sosyal alan yer alır. Görseller proje render'larından alınmıştır; inşaat şu anda kaba yapım aşamasındadır.",
    facts: [
      { k: "Konum", v: "Gaziemir, İzmir" },
      { k: "Durum", v: "Kaba İnşaat Aşamasında" },
      { k: "Daire Tipleri", v: "1+1 (2 farklı tip)" },
      { k: "Toplam Daire", v: "238 Daire" },
    ],
    unitsT: "Daire Tipleri",
    unitsD: "İki farklı tipte, modern ve fonksiyonel 1+1 daire seçenekleri. (Metrekare bilgileri yakında eklenecektir.)",
    units: [
      { type: "1+1 — A Tipi", size: "— m²", d: "Modern ve pratik plan; canlı bir yaşam veya kira getirisi için ideal.", img: IMG.d1 },
      { type: "1+1 — B Tipi", size: "— m²", d: "Farklı cephe ve yerleşimle alternatif bir 1+1 seçeneği.", img: IMG.d2 },
    ],
    amenitiesT: "Sosyal Alanlar & Çarşı",
    amenitiesD: "Site içinde, ayağınıza gelen yaşam ve ticaret olanakları.",
    amenities: [
      { t: "Yüzme Havuzu & Sosyal Alan", d: "Havuz, şezlong alanları ve geniş ortak yaşam alanları.", img: IMG.pool },
      { t: "Çarşı — Market & Mağazalar", d: "Market, mağaza ve hizmet birimlerinden oluşan canlı bir çarşı.", img: IMG.carsiCephe },
      { t: "Kafe & Restoran", d: "Site içinde kafe ve restoran alanları.", img: IMG.carsi },
      { t: "Peyzaj & Teraslar", d: "Yeşil peyzaj alanları, yürüyüş yolları ve geniş teraslar.", img: IMG.social },
    ],
    extras: ["Yüzme Havuzu", "Çarşı & Market", "Kafe & Restoran", "Peyzaj & Yürüyüş Yolları", "Geniş Teraslar", "Açık Otopark"],
    galleryT: "Görseller",
    backToProjects: "Projeye Dön",
  },
};

const en: typeof tr = {
  locale: "en",
  nav: {
    home: "Home",
    about: "About the Project",
    projects: "Apartments",
    services: "Why Loft 777",
    contact: "Contact",
    catalog: "Digital Catalog",
    cta: "Get a Quote",
  },
  hero: {
    kicker: "Camsan Koparan Group · Gaziemir / Izmir",
    lines: ["A new way", "of living in", "Gaziemir:"],
    last: "Loft 777.",
    sub: "A lively shopping arcade below, modern 1+1 apartments above, and a pool-side social area at its heart. A new address in Izmir Gaziemir, designed both to live in and to invest.",
    ctaPrimary: "Get Price & Floor Plan",
    ctaSecondary: "Call Us",
    video: "",
  },
  about: {
    kicker: "About Loft 777",
    title1: "In the heart of the city,",
    title2: "everything at your feet.",
    body: "Loft 777 is a new-generation mixed-use project in Izmir Gaziemir that brings daily life together at a single address — with its lively arcade of markets, cafés and shops, its pool-side social area and its modern 1+1 apartments. Designed both to live in and as an appreciating investment.",
    badge: "TOTAL APARTMENTS",
    more: "Explore the Project",
    points: [
      { t: "Central Location", d: "In the heart of Gaziemir; close to transport, shopping and main arteries." },
      { t: "Mixed-Use Living", d: "An arcade on the ground floor, homes above — everything you need in one building." },
      { t: "Smart 1+1 Apartments", d: "Practical, modern and functional plans; ideal both to live in and to invest." },
    ],
  },
  aboutPage: {
    kicker: "About the Project",
    title: "Loft 777 — a new way of living in Gaziemir",
    intro: "Loft 777 is a 238-unit mixed-use living project developed by Camsan Koparan Group Inc. in Izmir Gaziemir. With its lively arcade, pool-side social area and modern 1+1 apartments, it brings comfort, commerce and social life together at a single address.",
    visionT: "Concept",
    visionD: "An arcade below, homes above and a pool-side social area at the centre — an integrated way of living where you can experience all of daily life within the site.",
    missionT: "Our Approach",
    missionD: "Bringing together modern architecture, quality workmanship and functional apartment plans to offer both an enjoyable life and a sound investment.",
    valuesT: "Highlights",
    values: [
      { t: "238 Apartments", d: "All 1+1, with two different types and varied façade options." },
      { t: "Lively Arcade", d: "Markets, cafés, restaurants and shops bringing commerce and services to your door." },
      { t: "Social Life", d: "Swimming pool, wide landscaped areas and social amenities." },
      { t: "A Trusted Signature", d: "A project developed under the assurance of Camsan Koparan Group Inc." },
    ],
  },
  stats: [
    { big: "238", small: "Apartments" },
    { big: "1+1", small: "Apartment Types" },
    { big: "Arcade", small: "Mixed-Use Living" },
    { big: "Gaziemir", small: "Izmir" },
  ],
  projectsHome: {
    kicker: "Project",
    title1: "One signature,",
    title2: "a complete life.",
    all: "View the Project",
    incele: "View",
  },
  projectsPage: {
    kicker: "Apartments",
    title: "Loft 777 Apartments",
    intro: "Modern 1+1 apartments and a lively arcade in the heart of Gaziemir.",
    ongoing: "Ongoing Project",
    completed: "Completed Projects",
    soon: "Our new projects are coming soon on this page.",
    detail: "View Project",
  },
  services: {
    kicker: "Why Loft 777?",
    title1: "A way of living that",
    title2: "makes life easier.",
    items: [
      { no: "01", t: "Central Location", d: "In Izmir Gaziemir; a valuable location close to transport, shopping and main arteries." },
      { no: "02", t: "Arcade & Commerce", d: "A lively arcade of markets, cafés, restaurants and shops; services at your door." },
      { no: "03", t: "Social Amenities", d: "Swimming pool, wide landscaped areas and enjoyable shared living spaces." },
      { no: "04", t: "1+1 Apartments", d: "Practical and modern; ideal both to live in and for rental income." },
    ],
  },
  servicesPage: {
    kicker: "Why Loft 777",
    title: "What sets Loft 777 apart",
    intro: "Location, arcade, social life and smart apartment plans — all in a single project.",
  },
  cta: {
    kicker: "Contact",
    title1: "Reserve your place",
    title2: "at Loft 777 today.",
    body: "Leave your details for the price list, floor plans and apartment options, and our team will get back to you as soon as possible.",
    call: "Call Us",
    email: "Send an Email",
  },
  contactPage: {
    kicker: "Contact",
    title: "Get in Touch",
    intro: "Contact us for prices, floor plans and apartment details about Loft 777.",
    addressT: "Address",
    address: "Dokuz Eylul Mah. 694 Sok. No:5, Gaziemir / Izmir",
    phoneT: "Phone",
    phone: "+90 232 237 7 237",
    mailT: "E-mail",
    mail: "info@camsankoparan.com",
    formName: "Full Name",
    formMail: "E-mail",
    formPhone: "Phone",
    formMsg: "Your Message",
    formSend: "Send",
  },
  footer: {
    tagline: "A new-generation mixed-use project in Izmir Gaziemir — with its arcade, pool and modern 1+1 apartments. Under the assurance of Camsan Koparan Group Inc.",
    cols: [
      { title: "Project", links: ["Apartments (1+1)", "Social Areas", "Arcade & Commerce", "Location"] },
      { title: "Corporate", links: ["About the Project", "Camsan Koparan Group", "Why Loft 777"] },
      { title: "Contact", links: ["Gaziemir / Izmir", "+90 232 237 7 237", "info@camsankoparan.com"] },
    ],
    rights: "All rights reserved.",
    credit: "Design & Management",
  },
  callForm: {
    tab: "Call Me Back",
    title: "Request a Call",
    sub: "Leave your details and our team will call you back shortly.",
    name: "Full Name",
    phone: "Phone",
    msg: "Your message (optional)",
    send: "Send",
    sending: "Sending…",
    success: "Thank you! We will call you back shortly.",
    error: "Something went wrong, please try again.",
  },
  formExtra: {
    unitLabel: "Apartment type you're interested in",
    unitPlaceholder: "Select apartment type (optional)",
    unitOptions: [
      { value: "1+1-a", label: "1+1 Type A" },
      { value: "1+1-b", label: "1+1 Type B" },
      { value: "farketmez", label: "No preference" },
    ],
    kvkkText:
      "I consent to the processing of my personal data for the purpose of being contacted.",
    kvkkRequired: "Please check the consent box to continue.",
  },
  gallery: {
    kicker: "Gallery",
    title1: "Explore the",
    title2: "project up close.",
    hint: "Click an image to enlarge",
    categories: {
      all: "All",
      exterior: "Exterior",
      interior: "Interior",
      social: "Social Area",
      commercial: "Arcade",
    },
    items: [
      { img: "/renders/dis-cephe-gece-1.jpg", cat: "exterior", caption: "Façade — night" },
      { img: "/renders/dis-cephe-aksam.jpg", cat: "exterior", caption: "Façade — evening" },
      { img: "/renders/dis-cephe-genel.jpg", cat: "exterior", caption: "Overview" },
      { img: "/renders/hava-genel-gece.jpg", cat: "exterior", caption: "Aerial — night" },
      { img: "/renders/hava-tepeden.jpg", cat: "exterior", caption: "Top view" },
      { img: "/renders/daire-salon-1.jpg", cat: "interior", caption: "Living room" },
      { img: "/renders/daire-salon-2.jpg", cat: "interior", caption: "Living & seating" },
      { img: "/renders/daire-salon-3.jpg", cat: "interior", caption: "Living space" },
      { img: "/renders/daire-genel.jpg", cat: "interior", caption: "Apartment overview" },
      { img: "/renders/daire-mutfak.jpg", cat: "interior", caption: "Kitchen" },
      { img: "/renders/teras-balkon.jpg", cat: "interior", caption: "Terrace & balcony" },
      { img: "/renders/avlu-havuz-kus.jpg", cat: "social", caption: "Swimming pool" },
      { img: "/renders/sosyal-alan.jpg", cat: "social", caption: "Social area" },
      { img: "/renders/carsi-cephe.jpg", cat: "commercial", caption: "Arcade frontage" },
      { img: "/renders/carsi-magaza.jpg", cat: "commercial", caption: "Shops" },
      { img: "/renders/carsi-kafe.jpg", cat: "commercial", caption: "Café & restaurant" },
      { img: "/renders/carsi-gece.jpg", cat: "commercial", caption: "Arcade — night" },
    ],
  },
  construction: {
    kicker: "Construction Status",
    title1: "A transparent process,",
    title2: "updated every week.",
    status: "Under Construction (Structural Phase)",
    body: "Our construction is currently in the structural phase. We run the process transparently and will share progress every week with up-to-date drone footage.",
    steps: ["Foundation & Structure", "Interior Works", "Façade & Landscape", "Delivery"],
    currentStep: 0,
    droneTitle: "Weekly Drone Footage",
    droneSoon: "Up-to-date construction visuals will be shared here very soon.",
  },
  faq: {
    kicker: "FAQ",
    title1: "Answers to",
    title2: "your questions.",
    items: [
      {
        q: "What stage is the project at, and when is delivery?",
        a: "The project is currently in the structural phase. Please contact our sales team for the exact delivery date.",
      },
      {
        q: "What are the apartment types and sizes?",
        a: "All apartments are 1+1, available in two types with different façade options. Contact us for up-to-date floor areas and plans.",
      },
      {
        q: "How can I get pricing information?",
        a: "Fill in the 'Get a Quote' form on the site for the price list and floor plans, and our team will reach out shortly.",
      },
      {
        q: "Where is the project and how is access?",
        a: "In Izmir Gaziemir; a central location close to the airport, the İZBAN rail line and main transport routes.",
      },
      {
        q: "Are there an arcade and social areas on site?",
        a: "Yes. A ground-floor arcade with a market, café and shops, plus a wide social area with a swimming pool at the centre.",
      },
      {
        q: "Is it suitable for investment?",
        a: "With its 1+1 apartments and the lively arcade below, the project is designed both for living and for rental income / investment.",
      },
    ],
  },
  location: {
    kicker: "Location",
    title1: "In the very heart",
    title2: "of Gaziemir.",
    body: "In Izmir Gaziemir; a privileged location at the centre of transport, shopping and daily life.",
    addressTitle: "Address",
    mapQuery: "Gaziemir, İzmir, Türkiye",
    points: [
      { t: "Airport", d: "Close to Adnan Menderes Airport" },
      { t: "İZBAN & Transit", d: "Easy access to the commuter rail and main arteries" },
      { t: "Highway", d: "Near ring road and highway connections" },
      { t: "Centre", d: "Shopping, schools and daily needs nearby" },
    ],
  },
  catalog: {
    title: "Digital Catalog",
    subtitle: "Loft 777 — Camsan Koparan Group 2026",
    hint: "Use the arrows or your keyboard to navigate",
    pages: [
      { title: "Loft 777", caption: "A new way of living in Gaziemir — Brochure 2026", img: IMG.hero },
      { title: "Project Concept", caption: "A lively arcade below, modern homes above, a pool-side social area at the centre.", img: IMG.projHero },
      { title: "Location", caption: "Izmir Gaziemir — central, close to the airport, İZBAN rail and main arteries.", img: IMG.aerial },
      { title: "1+1 Apartments", caption: "Modern, functional 1+1 apartments in two different types.", img: IMG.d1 },
      { title: "Interiors", caption: "Smart-plan living room, open kitchen and refined finishes.", img: IMG.d2 },
      { title: "Social Life", caption: "Swimming pool, wide landscaping and enjoyable shared areas.", img: IMG.pool },
      { title: "Arcade & Commerce", caption: "A lively arcade with a market, café and shops at your door.", img: IMG.carsi },
      { title: "Contact", caption: "Gaziemir / Izmir — +90 232 237 7 237 · info@camsankoparan.com", img: IMG.carsiCephe },
    ],
  },
  project: {
    slug: "loft-777",
    name: "Loft 777",
    location: "Gaziemir, Izmir",
    status: "Under Construction",
    hero: IMG.projHero,
    tagline: "A new way of living in Gaziemir, with its arcade, pool and modern 1+1 apartments.",
    overviewT: "About the Project",
    overview: "Loft 777 is a 238-unit mixed-use living project in Izmir Gaziemir. Its ground floor hosts a lively arcade of markets, cafés, restaurants and shops; its upper floors hold modern 1+1 apartments; and at its centre lies a wide social area with a swimming pool. Images are taken from project renders; construction is currently in the structural phase.",
    facts: [
      { k: "Location", v: "Gaziemir, Izmir" },
      { k: "Status", v: "Under Construction" },
      { k: "Unit Types", v: "1+1 (2 different types)" },
      { k: "Total Units", v: "238 Apartments" },
    ],
    unitsT: "Apartment Types",
    unitsD: "Modern and functional 1+1 apartments in two different types. (Floor areas will be added soon.)",
    units: [
      { type: "1+1 — Type A", size: "— m²", d: "A modern, practical plan; ideal for living or for rental income.", img: IMG.d1 },
      { type: "1+1 — Type B", size: "— m²", d: "An alternative 1+1 option with a different façade and layout.", img: IMG.d2 },
    ],
    amenitiesT: "Social Areas & Arcade",
    amenitiesD: "Living and commerce facilities right at your doorstep within the site.",
    amenities: [
      { t: "Swimming Pool & Social Area", d: "Pool, lounge areas and wide shared living spaces.", img: IMG.pool },
      { t: "Arcade — Markets & Shops", d: "A lively arcade of markets, shops and service units.", img: IMG.carsiCephe },
      { t: "Café & Restaurant", d: "On-site café and restaurant areas.", img: IMG.carsi },
      { t: "Landscape & Terraces", d: "Green landscaped areas, walking paths and wide terraces.", img: IMG.social },
    ],
    extras: ["Swimming Pool", "Arcade & Market", "Café & Restaurant", "Landscape & Walking Paths", "Wide Terraces", "Open Parking"],
    galleryT: "Gallery",
    backToProjects: "Back to Project",
  },
};

export type Dict = typeof tr;

export function getDict(locale: Locale): Dict {
  return locale === "en" ? en : tr;
}
